### ISSUE TITLE
Precomputed Scores

### ISSUE THREAD

**Issue by Haoxiang-Wang** [mansheej/data_diet#1]
Hi, could you provide some precomputed GraNd or EL2N scores on CIFAR-10 & CIFAR-100? (For example, this [paper](https://pluskid.github.io/influence-memorization/) provides download links to their pre-computed scores with the original dataset order) That could be really helpful. Thanks!

**Comment by mansheej** [comment]
Hi, I will make an update to the repository with a link to pre-computed scores and some other changes later this month. In the meantime, if you send me an email to mansheej@stanford.edu, I can send you a reply with the scores so that you won't have to wait.

**Comment by AlessioQuercia** [comment]
Hi, I see that the pre-computed scores are not published yet. It would be also interesting to have the indices of samples of the subsets that work well for you, as mentioned in the paper (e.g. the 50% subset for CIFAR10).
